### PR TITLE
Add cm performance profiles

### PR DESCRIPTION
**Pull request by ZjemCiKolege**
Need powersave and ondemand governor

### CODE REVIEW

**Comment by MarcKe** [comment]
None of those governors is actually made for our device.

**Comment by MarcKe** [comment]
Btw, we can still do this, but I would prefer some adjusted pegasusq settings and maybe reduced cpufreq, etc.

**Comment by JustArchi** [comment]
We can tweak PegasusQ variables, definitely

**Comment by ZjemCiKolege** [comment]
I would like to know why no one could turn those governors? :>

Blanced PegasusQ
Powersave edited PegasusQ
Performance performance

**Comment by JustArchi** [comment]
Performance is not working with multicores without this patch - https://github.com/ArchiDroid/ArchiKernel/commit/9989a51c1384027c8fa4f5f6b93220eb5fbed8cc

**Comment by MarcKe** [comment]
This commit is in the kernel. Anyways, performance is still a stupid governor in my eyes.
Id rather also modify pegasusq to hotplug faster and raise the cpu freq earlier for performance.

**Comment by JustArchi** [comment]
Performance is good especially when you want to benchmark stuff on 100% CPU. Also, overhead of this governor is equal to zero, as opposed to pegasusq polling mode.

But I agree, even when targetting for performance, tweaking pegasusq is better idea, mostly due to battery reasons.

**Pull request closed without merging**
